apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-compose-app
spec:
  selector:
    matchLabels:
      app: docker-compose-app
  replicas: 6
  template:
    metadata:
      labels:
        app: docker-compose-app
    spec:
      containers:
        - name: docker-compose-app
          image: docker-compose-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: docker-compose-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: docker-compose-app
  type: NodePort
