name: Docker Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set Timestamp
      id: vars
      run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build and Tag the Docker Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/Rbabinski2000/docker-compose-image:latest
        docker tag ghcr.io/Rbabinski2000/docker-compose-image:latest ghcr.io/Rbabinski2000/docker-compose-image:${{ env.timestamp }}

    - name: Push Docker Images to GitHub Container Registry
      run: |
        docker push ghcr.io/Rbabinski2000/docker-compose-image:latest
        docker push ghcr.io/Rbabinski2000/docker-compose-image:${{ env.timestamp }}
